config/routes.rb
Rails.application.routes.draw do
  get "/about" => 'home#about'
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete '/logout',  to: 'sessions#destroy'

  get "/signup" => "users#new"
  root 'accounts#index'
  get "months" => "accounts#months"
  get "months/:month" => "accounts#show_month"
  get "accounts/category/:category_id" => "accounts#category"
  resources :categories
  resources :accounts
  resources :users, only: [:show, :create, :edit, :update, :destroy]
end

app/models/account.rb
class Account < ApplicationRecord
  default_scope -> {order(created_at: :desc)}
  validates :money, presence: true, numericality: { only_integer: true }
  validates :body, length: { maximum: 50 }
  belongs_to :category
  belongs_to :user
  
  def self.search(search) 
    if search
      where(['body LIKE ?', "%#{search}%"])
    else
      all 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope -> {order(created_at: :desc)}
  validates :title, presence: true
  validates :body, length: { maximum: 140 }
  has_many :accounts, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length:{maximum: 50}
  validates :email, presence: true, length:{maximum: 255}, 
  format: {with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :accounts, dependent: :destroy
  has_many :categories, dependent: :destroy
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  before_action :correct_user_account, only: [:show, :edit, :update, :destroy]


  def index
    @accounts = Account.where(user_id: current_user.id).search(params[:search])
    sum
  end

  def new
    @account = Account.new
  end

  def create
    @account = current_user.accounts.build(account_params)
    change_account
    if @account.save
      flash[:notice] = "作成しました"
      redirect_to @account
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end
  
  def update
    change_account
    if @account.update(account_params)
      flash[:notice] = "編集しました"
      redirect_to @account
    else
      render 'edit'
    end
  end
  
  def destroy
    @account.destroy
    flash[:notice] = "削除しました"
    redirect_to accounts_path
  end
  
  def category
    @accounts = Account.where(category_id:params[:category_id])
    @account = Account.find_by(category_id:params[:category_id])
    sum
  end
  
  def months
  end
  
  def show_month
    @accounts = Account.where(month:params[:month].to_i, user_id: current_user.id)
    @account = Account.find_by(month:params[:month])
    sum
  end
  
  
  
  private
  
    def set_account
      @account = Account.find_by(id: params[:id])
    end
    
    def change_account
      @account.year = params[:year]
      @account.month = params[:month]
      @account.date = params[:date]
      @account.week = params[:week]
    end

    def account_params
      params.require(:account).permit(:year, :month, :date, :week, :money, 
                                    :category_id, :body, :user_id)
    end
    
    def correct_user_account
      @account = Account.find_by(id: params[:id])
      if current_user.id != @account.user_id
        flash[:notice] = "権限がありません"
        redirect_to root_url
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include AccountsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  private
  
    def logged_in_user
      unless logged_in?
        flash[:notice] = "ログインしてください"
        redirect_to login_url
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  before_action :correct_user_category, only: [:show, :edit, :update, :destroy]
  

  def index
    @categories = Category.where(user_id: current_user.id)
  end

  def new
    @category = current_user.categories.build
  end
  
  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      flash[:notice] = "カテゴリを作成しました"
      redirect_to @category
    else
      render 'new'
    end
  end
  
  def show
    @accounts = @category.accounts
    sum
  end

  def edit
  end
  
  def update
    if @category.update(category_params)
      flash[:notice] = "編集しました"
      redirect_to @category
    else
      render 'edit'
    end
  end
  
  def destroy
    @category.destroy
    flash[:notice] = "削除しました"
    redirect_to categories_path
  end
  
  private
  
    def set_category
      @category = Category.find(params[:id])
    end
  
    def category_params
      params.require(:category).permit(:title, :body, :user_id)
    end
    
    def correct_user_category
      @category = Category.find(params[:id])
      if current_user.id != @category.user_id
        flash[:notice] = "権限がありません"
        redirect_to root_url
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :ban_login_user, only: [:new, :create]

  def new
  end
  
  def create
      user = User.find_by(email: params[:session][:email])
      if user && user.authenticate(params[:session][:password])
          login(user)
          current_user
          flash[:notice] = "ログインしました"
          redirect_to root_url
      else
          flash.now[:notice] = 'メールアドレスまたはパスワードが間違っています'
          render 'new'
      end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to login_path
  end
  
  private
    def ban_login_user
      if session[:user_id]
        flash[:notice] = "すでにログインしています"
        redirect_to root_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :ban_login_user, only: [:new, :create]

  def new
    @user = User.new
  end

  def show
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "ユーザーを作成しました"
        redirect_to @user
    else
        render 'new'
    end
  end

  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを変更しました"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
     @user.destroy
     flash[:notice] = "ユーザーを削除しました"
     redirect_to root_path
  end
  
  private
    def set_user
       @user = User.find(params[:id])
    end
    
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    def correct_user
      if current_user.id != params[:id].to_i
        flash[:notice] = "権限がありません"
        redirect_to root_url
      end
    end
    
    def ban_login_user
      if session[:user_id]
        flash[:notice] = "すでにログインしています"
        redirect_to root_path
      end
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
    def sum
        @sum = @accounts.sum(:money)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(title = "")
        if title.empty?
            "家計簿アプリ"
        else
            title + " | 家計簿アプリ"
        end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def login(user)
    session[:user_id] = user.id
  end

  def logout
    session.delete(:user_id)
  end

  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/_accounts_form.html.erb
<table class="table_first">
    <thead>
    <tr>
        <th>日付</th>
        <th>支出</th>
        <th>カテゴリ</th>
        <th>詳細</th>
        <th colspan="2"></th>
    </tr>
    </thead>
    <tbody>
    
    <% @accounts.each do |account| %>
    <tr>
        <td><%= "#{account.year}年 #{account.month}月 #{account.date}日 #{account.week}曜日"%></td>
        <td><%= "#{account.money}円" %></td>
        <td><%= link_to account.category.try(:title), "/accounts/category/#{account.category_id}" %></td>
        <td><%= account.body %></td>
        <td><%= link_to "編集", edit_account_path(account) %></td>
        <td><%= link_to "削除", account, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
    </tr>
    <% end %>
    
    </tbody>
</table>

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
<%= render partial: 'shared/errors', locals:{ object: @account } %>

<p class="form_account">
<%= select_tag :year,
    options_for_select(("2015".."2019").to_a, selected: @account.year) %>年
    
<%= select_tag :month,
    options_for_select(("1".."12").to_a, selected: @account.month) %>月
    
<%= select_tag :date,
    options_for_select(("1".."31").to_a, selected: @account.date) %>日
    
<%= select_tag :week,
    options_for_select(["月", "火", "水", "木", "金", "土", "日"], selected: @account.week) %>曜日
</p>

<p class="form_account">
    <% @categories = current_user.categories.where(user_id: current_user.id) %>
    <%= f.label :category %>
    <%= select :account, :category_id, @categories.map{|t| [t.title, t.id]} %>
</p>
<p class="form_account">
      <%= f.label :body %><br>
      <%= f.text_area :body, placeholder: "説明事項があれば記入", size: "40" %>
</p>

<p class="form_account">
<%= f.text_field :money, placeholder: "金額" %>円
</p>
<p class="form_account">
 <%= f.submit "実行" %>
</p>
<% end %>

app/views/accounts/_sum.html.erb
<table>
    <tr>
        <td><strong>合計: </strong></td>
        <td><%= @sum %>円</td>
    </tr>
</table>

app/views/accounts/category.html.erb
<h1><%= @account.category.title %>の詳細</h1>

<%= render "accounts_form" %>
<br>

<%= render 'sum' %>

app/views/accounts/edit.html.erb
<% provide(:title, "編集") %>
<h1>編集ページ</h1>

<%= render 'form' %>

<%= link_to '戻る', accounts_path %>

app/views/accounts/index.html.erb
<% if @accounts.any? %>
<h1>家計簿一覧</h1>

<!--  検索拡張機能  -->
<p class="account_search">詳細検索</p>
<%= form_tag(accounts_path, :method => 'get' ) do %>
  <%= text_field_tag :search %>
  <%= submit_tag '検索', :name => nil %>
<% end %>
<br>
<%= render "accounts_form" %>
<br>

<%= render 'sum' %>

<% else %>
<h2>まだ家計簿がありません。</h2>
<% end %>

app/views/accounts/months.html.erb
<% provide(:title, "月別") %>
<h2 class="count_top">月ごとの作成数</h2>
<ul>
<% (1..12).each do |i| %>
  <li class="month_count"><%= link_to "#{i}月", "/months/#{i}" %> (<%= current_user.accounts.where(month:i).count %>)</li>
<% end %>  
</ul>  
<br><br>

app/views/accounts/new.html.erb
<% provide(:title, "新規") %>

<%= form_for(@account) do |f| %>
<%= render partial: 'shared/errors', locals:{ object: @account } %>

<p class="form_account">
<%= select_tag :year,
    options_for_select(("2015".."2019").to_a, selected: Date.today.year) %>年  

<%= select_tag :month,
    options_for_select(("1".."12").to_a, selected: Date.today.month) %>月
    
<%= select_tag :date,
    options_for_select(("1".."31").to_a, selected: Date.today.day) %>日
    
<% youbi = %w[日 月 火 水 木 金 土] %>
<%= select_tag :week,
    options_for_select(youbi, selected: youbi[Date.today.cwday]) %>曜日
</p>

<p class="form_account">
    <% @categories = current_user.categories.where(user_id: current_user.id) %>
    <%= f.label :category %>
    <%= select :account, :category_id, @categories.map{|t| [t.title, t.id]} %>
</p>
<p class="form_account">
      <%= f.label :body %><br>
      <%= f.text_area :body, placeholder: "説明事項があれば記入", size: "40" %>
</p>

<p class="form_account">
<%= f.text_field :money, placeholder: "金額" %>円
</p>

<p class="form_account">
 <%= f.submit "実行" %>
</p>
<% end %>

app/views/accounts/show.html.erb
<% provide(:title, "詳細") %>
<h1>詳細ページ</h1>
<p>
  <strong>日付:</strong>
  <%= "#{@account.year}年 #{@account.month}月 #{@account.date}日 #{@account.week}曜日"%>
</p>

<p>
  <strong>金額:</strong>
  <%= @account.money %>円
</p>

<p>
  <strong>カテゴリ:</strong>
  <%= @account.category.try(:title) %>
</p>
<p>
  <strong>詳細:</strong>
  <%= @account.body %>
</p>


<%= link_to "家計簿一覧へ", accounts_path %>

app/views/accounts/show_month.html.erb
<% provide(:title, "月別") %>
<% if @accounts.any? %>
  <h1><%= @account.month %>月の詳細</h1>
  <%= render 'accounts_form' %>
  <br>
  <%= render 'sum' %>
  <br>
  <%= link_to "戻る", "/months" %>
<% else %>
  <h2>まだ家計簿がありません。</h2>
  <%= link_to "戻る", "/months" %> | 
  <%= link_to "新規追加", new_account_path %>
<% end %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
<%= render partial: 'shared/errors', locals:{object: @category} %>

    <p class="form_category">
      <%= f.label :title %><br>
      <%= f.text_field :title, placeholder: "(例)食費" %>
    </p>
    
    <p class="form_category">
      <%= f.label :body %><br>
      <%= f.text_area :body, placeholder: "説明事項があれば記入", size: "40" %>
    </p>
    
    <p class="form_category">
      <%= f.submit "実行" %>
    </p>
<% end %>

app/views/categories/edit.html.erb
<% provide(:title, "カテゴリ編集") %>
<h1>カテゴリ編集ページ</h1>

<%= render 'form' %>
<br>
<%= link_to '戻る', categories_path %>

app/views/categories/index.html.erb
<% provide(:title, "カテゴリ一覧") %>

<% if @categories.any? %>
<h1>カテゴリ一覧</h1>
  <table id="category_table">
    <thead>
      <tr>
        <th>名前</th>
        <th>説明</th>
        <th colspan="2"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= link_to category.title, category %></td>
          <td><%= category.body %></td>
          <td><%= link_to '編集', edit_category_path(category) %></td>
          <td><%= link_to '削除', category, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
        </tr>
     <% end %>
    </tbody>
  </table>
<% else %>
<h2>まだカテゴリがありません。</h2>
<% end %>

app/views/categories/new.html.erb
<% provide(:title, "新規カテゴリ") %>

<%= render 'categories/form' %>

app/views/categories/show.html.erb
<% provide(:title, "カテゴリ詳細") %>

<p>
  <strong>名前:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>説明:</strong>
  <%= @category.body %>
</p>
<br>

<%= link_to '編集', edit_category_path(@category) %> |
<%= link_to 'カテゴリ一覧', categories_path %>
<br><br>
<% if @accounts.any? %>
  <h3>「<%= @category.title %>」の家計簿一覧</h3>
  <%= render 'accounts/accounts_form' %>
  <br>
  <%= render 'accounts/sum' %>
<% end %>

app/views/home/about.html.erb
<h2>家計簿アプリの使い方</h2>

<div class="about" id="about_top">
<h3>1.<%= link_to '新規追加', new_account_path %></h3>
<p>家計簿を<strong>新規追加</strong>できます。</p>
</div>

<div class="about">
<h3>2.<%= link_to '家計簿一覧', accounts_path %></h3>
<p>作成した家計簿が<strong>一覧表示</strong>され、それらの<strong>検索・編集・削除</strong>も行えます。</p>
<p>カテゴリ名のリンクをクリックするとその詳細が表示され、さらにそのカテゴリの家計簿が一覧表示されます。</p>
</div>

<div class="about">
<h3>3.<%= link_to '月ごとの詳細', "/months" %></h3>
<p>作成した家計簿を<strong>月ごとに分け</strong>、その数を表示します。</p>
<p>リンクをクリックするのその月の<strong>家計簿・合計金額</strong>を確認できます。</p>
</div>

<div class="about">
<h3>4.<%= link_to 'カテゴリ追加', new_category_path %></h3>
<p>カテゴリを新たに追加できます。</p>
<p>家計簿を<strong>カテゴリ分け</strong>するのに役立ちます。</p>
</div>

<div class="about">
<h3>5.<%= link_to 'カテゴリ一覧', categories_path %></h3>
<p>作成したカテゴリの<strong>名前・詳細</strong>が一覧表示され、それらの<strong>編集・削除</strong>も行えます。</p>
<p>名前のリンクをクリックするとその詳細が表示され、さらにそのカテゴリの家計簿が一覧表示されます。</p>
</div>
<br><br>

      

      

app/views/layouts/_head.html.erb
<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_header.html.erb
<header class="header">
        <div class="headerLeft">
            <h1 class="headerLogo">家計簿アプリ</h1>

            <ul class="headerNav">
                <div class="move-left">
                    <% if current_user %>
                        <li><%= link_to "Home", root_path %></li>
                    <% end %>
                <li><%= link_to "About", about_path %></li>
                </div>
            </ul>
        </div>
        <div class="headerRight">
            <% if current_user %>
                <%= link_to current_user.name, current_user %>
                <%= link_to "ログアウト", logout_path, method: :delete %>
            <% else %>
                <%= link_to "新規登録", signup_path %>
                <%= link_to "ログイン", login_path %>
            <% end %>
        </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/head" %>

  <body>
    <div id="wrapper">
      
    <%= render 'layouts/header' %>
     
    <% if current_user %>
      <nav>
        <%= link_to '新規追加', new_account_path %>
        <%= link_to '家計簿一覧', accounts_path %>
        <%= link_to '月ごとの詳細', "/months" %>
        <%= link_to 'カテゴリ追加', new_category_path %>
        <%= link_to 'カテゴリ一覧', categories_path %>
      </nav>
    <% end %>

    
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <h2><%= object.errors.count %>個エラーがあります</h2>
      <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
     <%= render 'shared/errors', object: f.object %>
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "user_form" %><br>

      <%= f.label :email %><br>
      <%= f.email_field :email, class: "user_form" %><br>
      

      <%= f.label :password %><br>
      <%= f.password_field :password, class: "user_form"  %><br>

      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation, class: "user_form" %><br>

      <%= f.submit yield(:button_text), class: "btn user_form" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "ユーザー編集") %>
<% provide(:button_text, '編集') %>
<h1>ユーザー編集</h1>

<div class="row">
<%= render 'form' %>
</div>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<% provide(:button_text, '新規登録') %>
<h1>新規登録</h1>
<div class="row">
<%= render 'form' %>
</div>

app/views/users/show.html.erb
<% provide(:title, "詳細") %>
<h1>ユーザー詳細ページ</h1>

<p>
  <strong>名前:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>メールアドレス:</strong>
  <%= @user.email %>
</p>

<%= link_to "編集", edit_user_path(@user) %> | 
<%= link_to "削除", @user, method: :delete, data: { confirm: "本当に削除しますか？" } %>